[package]
name = "common-staking"
version = "0.1.0"
authors = ["[your_name] <[your_email]>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
ink = { version = "5.0.0", default-features = false }

[features]
default = ["std"]
std = [
    "ink/std",
]
ink-as-dependency = []
