[package]
name = "enroll"
version = "0.1.0"
authors = ["Cardinal"]
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
ink = { version = "5.0.0", default-features = false }

[features]
default = ["std"]
std = [
    "ink/std",
]
ink-as-dependency = []
